name: Deploy Application

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:

  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::891612573605:role/github-oidc
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - name: Terraform Init and Plan
        run: |
          cd terraform
          terraform init
          terraform plan -out=tf.plan
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tf.plan
          retention-days: 1

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::891612573605:role/github-oidc
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform/
      - name: Terraform Init and Apply
        run: |
          cd terraform
          terraform init
          terraform apply tf.plan