name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::891612573605:role/github-oidc
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - name: Download Latest Plan Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: terraform-plan.yml
          name: terraform-plan
          path: terraform/
      - name: Download application artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: terraform-plan.yml
          name: application
          path: dist/
      - name: Terraform Init and Apply
        run: |
          cd terraform
          terraform init
          terraform apply tf.plan
